site_name: privacynow.no
repo_url: https://github.com/knut-erik/privacynow/
site_url: https://privacynow.no
site_author: knut-erik, Privacy Now
site_description: >-
  Documentation related to protecting your information using digital devices.

edit_uri: edit/main/docs
copyright: >
  Copyright &copy; privacynow.no
theme:
  name: material
  custom_dir: overrides/
  logo: assets/icons/privacynow_white.svg
  favicon: assets/icons/privacynow_black.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
exclude_docs: |
  presentations/*

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/knut-erik/privacynow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/knuterikhollund/
extra_css:
  - assets/css/privacynow.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - admonition
  - toc:
        permalink: true
plugins:
    - search
    - awesome-pages
    - git-revision-date-localized:
        type: date
    - mkdocs-simple-hooks:
        hooks:
          on_post_build: "docs.hooks:copy_folders_on_build"
